name: Deploy React App to AKS

on:
  push:
    branches:
      - main

env:
  ACR_NAME: acrlabregistry
  RESOURCE_GROUP: rg-tfstate
  CLUSTER_NAME: aks-lab
  IMAGE_NAME: react-lab-app

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.ARM_CLIENT_ID }}
        tenant-id: ${{ secrets.ARM_TENANT_ID }}
        subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}

    - name: Build and Push Docker image to ACR
      run: |
        az acr login --name $ACR_NAME
        docker build -t $ACR_NAME.azurecr.io/$IMAGE_NAME:latest .
        docker push $ACR_NAME.azurecr.io/$IMAGE_NAME:latest

    - name: Get AKS credentials
      run: |
        az aks get-credentials --resource-group $RESOURCE_GROUP --name $CLUSTER_NAME --overwrite-existing

    - name: Deploy to AKS
      run: |
        kubectl apply -f k8s/
