name: Deploy React App to AKS

on:
  push:
    branches:
      - main

env:
  ACR_NAME: acrlabregistry
  RESOURCE_GROUP: rg-tfstate
  CLUSTER_NAME: aks-lab
  IMAGE_NAME: react-lab-app

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Azure Login with OIDC
      uses: azure/login@v1
      with:
        client-id: b1ba8665-4227-4d0b-bcb1-ceb6f7d336cc
        tenant-id: f6fa9643-70a9-454c-8d0b-3cfc7c492750
        subscription-id: bb51bc68-387c-4f21-9046-8e1536a2d237

    - name: Build and Push Docker image to ACR
      run: |
        az acr login --name $ACR_NAME
        docker build -t $ACR_NAME.azurecr.io/$IMAGE_NAME:latest .
        docker push $ACR_NAME.azurecr.io/$IMAGE_NAME:latest

    - name: Get AKS credentials
      run: |
        az aks get-credentials --resource-group $RESOURCE_GROUP --name $CLUSTER_NAME --overwrite-existing

    - name: Deploy to AKS
      run: |
        kubectl apply -f k8s/
